
/**
 * This file is autogenerated, do not modify directly
 * Generated on Wed Jun 19 2024 15:10:45 GMT+0000 (Coordinated Universal Time) 
*/

/* eslint-disable @7pace/rules/no-hard-coded-colors, @7pace/rules/no-non-system-product-color-values */
enum ThemeSystem {
	Atlassian = "atlassian",
	AzDo = "azdo",
	Default = "default",
	Monday = "monday",
}
export default ThemeSystem;
