import { IconSlotType } from "../../slots/icon/types";


export const defaultIcons: Record<IconSlotType, string> = {
    [IconSlotType.ArrowUp]: "la-arrow-up",
    [IconSlotType.ArrowDown]: "la-arrow-down",
    [IconSlotType.ArrowUpRight]: "la-level-up-alt",
    [IconSlotType.ChevronLeft]: "la-angle-left",
    [IconSlotType.ChevronRight]: "la-angle-right",
    [IconSlotType.ChevronDown]: "la-angle-down",
    [IconSlotType.ChevronDoubleDown]: "la-angle-double-down",
    [IconSlotType.ChevronUp]: "la-angle-up",
    [IconSlotType.Comment]: "la-comment",
    [IconSlotType.Bin]: "la-trash-alt",
    [IconSlotType.Pen]: "la-pen",
    [IconSlotType.Plus]: "la-plus",
    [IconSlotType.ZoomIn]: "la-search-plus",
    [IconSlotType.ZoomOut]: "la-search-minus",
    [IconSlotType.QuestionCircle]: "la-question-circle",
    [IconSlotType.Copy]: "la-copy",
    [IconSlotType.TimeFrame]: "la-calendar-check",
    [IconSlotType.Stack]: "la-bars",
    [IconSlotType.Calendar]: "la-calendar",
    [IconSlotType.Drag]: "la-arrows-alt",
    [IconSlotType.Close]: "la-times",
    [IconSlotType.Export]: "la-file-export",
    [IconSlotType.Gift]: "la-gift",
    [IconSlotType.Group]: "la-object-group",
    [IconSlotType.Sort]: "la-sort",
    [IconSlotType.Settings]: "la-cog",
    [IconSlotType.Expand]: "la-arrows-alt-v",
    [IconSlotType.School]: "la-school",
    [IconSlotType.Envelope]: "la-envelope",
    [IconSlotType.Rocket]: "la-rocket",
    [IconSlotType.Lightbulb]: "la-lightbulb",
    [IconSlotType.Minus]: "la-minus",
    [IconSlotType.Filter]: "la-filter",
    [IconSlotType.Import]: "la-file-import",
    [IconSlotType.Undo]: "la-undo",
    [IconSlotType.ExternalLink]: "la-external-link-alt",
    [IconSlotType.Check]: "la-check",
    [IconSlotType.Warning]: "la-exclamation-triangle"
};
