import { ThemeStyles } from "../defaultColorSchema";


/* eslint-disable @7pace/rules/no-hard-coded-colors */
export const darkThemeVariables: ThemeStyles = {
    ["--tt-palette-main-button"]: "#497BFA",
    ["--tt-palette-main-button-hov"]: "#5C88FA",
    ["--tt-palette-main-button-act"]: "#648FFA",
    ["--tt-palette-sec-button"]: "#2FA8A8",
    ["--tt-palette-sec-button-hov"]: "#44B1B1",
    ["--tt-palette-sec-button-act"]: "#4EB5B5",
    ["--tt-palette-contrast-button"]: "#E9EFFF",
    ["--tt-palette-contrast-button-hov"]: "#DDE3F2",
    ["--tt-palette-contrast-button-act"]: "#C6CCD9",
    ["--tt-palette-neg-button"]: "#F9826D",
    ["--tt-palette-neg-button-hov"]: "#FA8F7C",
    ["--tt-palette-neg-button-act"]: "#FA9583",
    ["--tt-palette-default-button"]: "#D2DEFE12",
    ["--tt-palette-default-button-hov"]: "#D2DEFE26",
    ["--tt-palette-default-button-act"]: "#D2DEFE33",
    ["--tt-palette-full-color-na"]: "#343A46",
    ["--tt-palette-full-color-alt-na"]: "#414856",
    ["--tt-palette-input-border"]: "#40485C",
    ["--tt-palette-input-border-hov"]: "#5C657B",
    ["--tt-palette-input-border-act"]: "#497BFA",
    ["--tt-palette-sec-button-border"]: "#8B94AA",
    ["--tt-palette-txt-gen"]: "#EFF0F1",
    ["--tt-palette-txt-gen-inverted"]: "#333333",
    ["--tt-palette-txt-sec"]: "#8B94AA",
    ["--tt-palette-txt-gen-contrast"]: "#ffffff",
    ["--tt-palette-txt-third"]: "#5C657B",
    ["--tt-palette-primary-background"]: "#1A2029",
    ["--tt-palette-secondary-background"]: "#E9EFFF",
    ["--tt-palette-tooltips-background"]: "#E9EFFF",
    ["--tt-palette-tooltips-background-dark-blue"]: "#1C5AF9",
    ["--tt-palette-button-on-contrast"]: "#708FA51A",
    ["--tt-palette-button-on-contrast-hov"]: "#708FA526",
    ["--tt-palette-button-on-contrast-act"]: "#708FA533",
    ["--tt-palette-light-background"]: "#D2DEFE0D",
    ["--tt-palette-secondary-hover"]: "#8EADFB1A",
    ["--tt-palette-general-hover"]: "#8EADFB33",
    ["--tt-palette-license-role"]: "#16C8C81A",
    ["--tt-palette-txt-alternative-red"]: "#BB6B64",
    ["--tt-palette-txt-alternative-blue"]: "#2351C7",
    ["--tt-palette-special-shadow"]: "#8EADFB0D",
    ["--tt-palette-special-shadow-hov"]: "#8EADFB26",
    ["--tt-palette-info-positive-sec"]: "#68C360",
    ["--tt-palette-info-positive-background"]: "#2B363A",
    ["--tt-palette-info-neutral-sec"]: "#497BFA",
    ["--tt-palette-info-neutral-background"]: "#282E38",
    ["--tt-palette-background-transparent-40"]: "#1A202966",
    ["--tt-palette-info-warning-sec"]: "#FCB23E",
    ["--tt-palette-info-warning-background"]: "#303121",
    ["--tt-palette-info-negative-sec"]: "#FA8577",
    ["--tt-palette-info-negative-background"]: "#322F38",
    ["--tt-palette-light-yellow-tag"]: "#FFB23F4D",
    ["--tt-palette-dark-yellow-tag"]: "#996B26",
    ["--tt-palette-light-green-tag"]: "#16C8C84D",
    ["--tt-palette-dark-green-tag"]: "#1C7878",
    ["--tt-palette-light-red-tag"]: "#FA85774D",
    ["--tt-palette-dark-red-tag"]: "#995047",
    ["--tt-palette-top-bar-background"]: "#282E38",
    ["--tt-palette-neutral-dark"]: "#3E434C",
    ["--tt-palette-tooltips-shadow-1"]: "#8EADFB12",
    ["--tt-palette-tooltips-shadow-2"]: "#8EADFB33",
    ["--tt-palette-button-shadow"]: "#1B1F230A",
    ["--tt-palette-primary-button-shadow"]: "#1B1F231A"
} as unknown;
