import { ThemeStyles } from "../defaultColorSchema";


/* eslint-disable @7pace/rules/no-hard-coded-colors */
export const lightThemeVariables: ThemeStyles = {
    ["--tt-palette-main-button"]: "#0094FF",
    ["--tt-palette-main-button-hov"]: "#1B85E5",
    ["--tt-palette-main-button-act"]: "#197ED9",
    ["--tt-palette-sec-button"]: "#16C8C8",
    ["--tt-palette-sec-button-hov"]: "#2FB4B4",
    ["--tt-palette-sec-button-act"]: "#2CAAAA",
    ["--tt-palette-contrast-button"]: "#282E38",
    ["--tt-palette-contrast-button-hov"]: "#3E434C",
    ["--tt-palette-contrast-button-act"]: "#484D56",
    ["--tt-palette-neg-button"]: "#FA8577",
    ["--tt-palette-neg-button-hov"]: "#E1776B",
    ["--tt-palette-neg-button-act"]: "#D57165",
    ["--tt-palette-default-button"]: "#708FA51A",
    ["--tt-palette-default-button-hov"]: "#708FA526",
    ["--tt-palette-default-button-act"]: "#708FA533",
    ["--tt-palette-full-color-na"]: "#F1F4F6",
    ["--tt-palette-full-color-alt-na"]: "#EAEEF2",
    ["--tt-palette-input-border"]: "#282E3833",
    ["--tt-palette-input-border-hov"]: "#282E3880",
    ["--tt-palette-input-border-act"]: "#0094FF",
    ["--tt-palette-sec-button-border"]: "#A7A7A7",
    ["--tt-palette-txt-gen"]: "#333333",
    ["--tt-palette-txt-gen-inverted"]: "#EFF0F1",
    ["--tt-palette-txt-sec"]: "#605E5C",
    ["--tt-palette-txt-gen-contrast"]: "#ffffff",
    ["--tt-palette-txt-third"]: "#DBDBDB",
    ["--tt-palette-primary-background"]: "#ffffff",
    ["--tt-palette-secondary-background"]: "#282E38",
    ["--tt-palette-tooltips-background"]: "#282E38",
    ["--tt-palette-tooltips-background-dark-blue"]: "#1C5AF9",
    ["--tt-palette-button-on-contrast"]: "#FFFFFF1A",
    ["--tt-palette-button-on-contrast-hov"]: "#FFFFFF26",
    ["--tt-palette-button-on-contrast-act"]: "#FFFFFF33",
    ["--tt-palette-light-background"]: "#282E380D",
    ["--tt-palette-background-transparent-40"]: "#FFFFFF66",
    ["--tt-palette-secondary-hover"]: "#708FA51A",
    ["--tt-palette-general-hover"]: "#708FA526",
    ["--tt-palette-license-role"]: "#16C8C81A",
    ["--tt-palette-txt-alternative-red"]: "#F76C6C",
    ["--tt-palette-txt-alternative-blue"]: "#32A9FB",
    ["--tt-palette-special-shadow"]: "#282E380D",
    ["--tt-palette-special-shadow-hov"]: "#282E3826",
    ["--tt-palette-info-positive-sec"]: "#68C360",
    ["--tt-palette-info-positive-background"]: "#EFF8EE",
    ["--tt-palette-info-neutral-sec"]: "#32A9FB",
    ["--tt-palette-info-neutral-background"]: "#EFF8FF",
    ["--tt-palette-info-warning-sec"]: "#FCB23E",
    ["--tt-palette-info-warning-background"]: "#FFF1DB",
    ["--tt-palette-info-negative-sec"]: "#FA8577",
    ["--tt-palette-info-negative-background"]: "#FFF7F6",
    ["--tt-palette-light-yellow-tag"]: "#FFB23F4D",
    ["--tt-palette-dark-yellow-tag"]: "#996B26",
    ["--tt-palette-light-green-tag"]: "#16C8C84D",
    ["--tt-palette-dark-green-tag"]: "#1C7878",
    ["--tt-palette-light-red-tag"]: "#FA85774D",
    ["--tt-palette-dark-red-tag"]: "#995047",
    ["--tt-palette-top-bar-background"]: "#282E38",
    ["--tt-palette-neutral-dark"]: "#3E434C",
    ["--tt-palette-tooltips-shadow-1"]: "#282E3812",
    ["--tt-palette-tooltips-shadow-2"]: "#282E3833",
    ["--tt-palette-button-shadow"]: "#1B1F230A",
    ["--tt-palette-primary-button-shadow"]: "#1B1F231A"
} as unknown;
